---
# tasks file for vsts-agent

- name: Create vsts user
  become: true
  user:
    name: vsts
    home: /opt/vsts

- name: Create VSTS agent work folder
  file:
    path: /var/vsts
    state: directory
    owner: vsts
    group: vsts
    mode: 0755

- name: Download and unpack VSTS agent
  become: true
  unarchive:
    src: "https://vstsagentpackage.azureedge.net/agent/{{ vstsagent.version }}/vsts-agent-linux-x64-{{ vstsagent.version }}.tar.gz"
    dest: /opt/vsts
    remote_src: yes

- name: Install git apt package
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
